# Generated by Django 6.0.6 on 2026-06-24 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Neighbourhood Clinic', max_length=120)),
                ('avg_consultation_minutes', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clinic settings',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In consultation'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('queue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['token_number'],
                'constraints': [models.UniqueConstraint(fields=('token_number', 'queue_date'), name='unique_token_per_day')],
            },
        ),
    ]
